management:
  endpoints:
    web:
      exposure:
        include: "*"
 
spring: 
  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate: 
      ddl-auto: update
 
greetingLanguage: English / spring config test0816

---
spring: 
  profiles: dev
greetingLanguage: French0816
---
spring: 
  profiles: prod
greetingLanguage: Spanish0816
