management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

greetingLanguage: English / spring config test08161

---
spring:
  profiles: dev
greetingLanguage: French08167
---
spring:
  profiles: prod
greetingLanguage: Spanish0816
